---
project: Lab Automation Project
kind: PIPELINE
name: Base Configuration
icon: organization,left, is-warm-grey
enabled: true
concurrency: 10
workspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Unconfigure vRA
stages:
  Unconfigure vRA:
    taskOrder:
    - Set Base Configuration
    tasks:
      Set Base Configuration:
        type: PowerShell
        input:
          script: |
            Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser
            python .\2121-reset-config.py
          username: administrator
          password: VMware1!
          useTLS: false
          trustCert: false
          host: 192.168.110.10
          workingDirectory: C:\hol-2121-lab-files
          arguments: [
            ]
          environmentVariables: {
            }
